sonar.projectKey=leninkart-order-service
sonar.projectName=LeninKart Order Service
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes,target/test-classes
sonar.exclusions=target/**
